// Generated by gencpp from file local_planning/MyFirstMsg.msg
// DO NOT EDIT!


#ifndef LOCAL_PLANNING_MESSAGE_MYFIRSTMSG_H
#define LOCAL_PLANNING_MESSAGE_MYFIRSTMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace local_planning
{
template <class ContainerAllocator>
struct MyFirstMsg_
{
  typedef MyFirstMsg_<ContainerAllocator> Type;

  MyFirstMsg_()
    : a(0.0)  {
    }
  MyFirstMsg_(const ContainerAllocator& _alloc)
    : a(0.0)  {
  (void)_alloc;
    }



   typedef double _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::local_planning::MyFirstMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::local_planning::MyFirstMsg_<ContainerAllocator> const> ConstPtr;

}; // struct MyFirstMsg_

typedef ::local_planning::MyFirstMsg_<std::allocator<void> > MyFirstMsg;

typedef boost::shared_ptr< ::local_planning::MyFirstMsg > MyFirstMsgPtr;
typedef boost::shared_ptr< ::local_planning::MyFirstMsg const> MyFirstMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::local_planning::MyFirstMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::local_planning::MyFirstMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::local_planning::MyFirstMsg_<ContainerAllocator1> & lhs, const ::local_planning::MyFirstMsg_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::local_planning::MyFirstMsg_<ContainerAllocator1> & lhs, const ::local_planning::MyFirstMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace local_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::local_planning::MyFirstMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::local_planning::MyFirstMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_planning::MyFirstMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::local_planning::MyFirstMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_planning::MyFirstMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::local_planning::MyFirstMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::local_planning::MyFirstMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d59eeb6f47744097bbc77f6e8d9be14";
  }

  static const char* value(const ::local_planning::MyFirstMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d59eeb6f4774409ULL;
  static const uint64_t static_value2 = 0x7bbc77f6e8d9be14ULL;
};

template<class ContainerAllocator>
struct DataType< ::local_planning::MyFirstMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "local_planning/MyFirstMsg";
  }

  static const char* value(const ::local_planning::MyFirstMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::local_planning::MyFirstMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 a\n"
;
  }

  static const char* value(const ::local_planning::MyFirstMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::local_planning::MyFirstMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyFirstMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::local_planning::MyFirstMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::local_planning::MyFirstMsg_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCAL_PLANNING_MESSAGE_MYFIRSTMSG_H
